apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: zlkf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zlkf
    app.kubernetes.io/part-of: byoc-app-osvm
  name: zlkf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: zlkf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: zlkf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-xrdy-tenant/byoc-app-osvm/zlkf@sha256:18183c36372383ec4cbd2309f4e56d45d6b99a51e1d6311394d739f69381770b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
