apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: zlkf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zlkf
    app.kubernetes.io/part-of: byoc-app-osvm
  name: zlkf
spec:
  rules:
  - host: zlkf-byoc-xrdy-tenant.apps.2ffd35266520e2f06924.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: zlkf
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
